"""users table

Revision ID: 0f2a050672e5
Revises: ed61446af2ed
Create Date: 2023-08-04 22:20:12.065957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2a050672e5'
down_revision = 'ed61446af2ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_age'), ['age'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_budget'), ['budget'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_phone'), ['phone'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone'))
        batch_op.drop_index(batch_op.f('ix_user_gender'))
        batch_op.drop_index(batch_op.f('ix_user_country'))
        batch_op.drop_index(batch_op.f('ix_user_budget'))
        batch_op.drop_index(batch_op.f('ix_user_age'))

    # ### end Alembic commands ###
