"""bookings table

Revision ID: a7dfc82872cc
Revises: 91b3c24c7135
Create Date: 2023-08-26 21:59:01.894531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7dfc82872cc'
down_revision = '91b3c24c7135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'BOOKED', name='bookingstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_booking_time'), ['booking_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_booking_time'))

    op.drop_table('booking')
    # ### end Alembic commands ###
